### ISSUE TITLE
Crash when image loaded asyncroneously with Glide

### ISSUE THREAD

**Issue by eugeneroz** [abdularis/ParallaxImageView#1]
java.lang.IllegalStateException: view.drawable must not be null
        at com.github.abdularis.piv.transformer.VerticalParallaxTransformer.apply(VerticalParallaxTransformer.kt:23)
        at com.github.abdularis.piv.ScrollTransformImageView.onDraw(ScrollTransformImageView.kt:41)
        at android.view.View.draw(View.java:16217)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)
        at android.view.View.updateDisplayListIfDirty(View.java:15214)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.updateDisplayListIfDirty(View.java:15209)
        at android.view.View.draw(View.java:15987)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
        at android.view.View.draw(View.java:16220)

**Comment by abdularis** [comment]
I've reproduced the same error using glide by

```
Glide .with(this)
                .load(R.drawable.img1)
                .into(holder.image)
```

the error was because `Horizontal and VerticalParallaxTransformer` class were not checking if the drawable is null.
also `Horizontal and VerticalScrollParallaxImageView` class is always in center crop mode, and Glide will crop the bitmap to fit the dimension of the view, so can't have parallax effect because the bitmap is cropped/fitted. you have to explicitly tell glide not to fit this bitmap.

```
Glide.with(this)
                .applyDefaultRequestOptions(RequestOptions.centerInsideTransform())
                .load(R.drawable.img1)
                .into(holder.image)
```
check this [here](https://github.com/abdularis/ParallaxImageView/releases/tag/1.1)
